### ISSUE TITLE
Documents unable to open 

### ISSUE THREAD

**Issue by stoverc** [jdeslip/arxiv-mobile#11]
Hi there! 

For the past week or so, any article I try to read gives an error mentioning an invalid pdf. Apparently, all articles are showing up as 0.0MB as well. 

I see that someone else mentioned the same issue in the Play store just a couple days ago; I also noticed a similar bug listed here from back in 2013. Not sure how all this is related, but I wanted to share. 

Thanks for the great app, and I hope it gets back up and running again soon!

**Comment by DrPhimor** [comment]
I have the same problem now with the version 2.0.6 an a Samsung Galaxy S5, installed via F-Droid (version 0.102.3).

**Comment by pliable-statistics** [comment]
@stoverc 
I figured out how to solve the problem. Just created pull request with fixes https://github.com/jdeslip/arxiv-mobile/pull/14

**Comment by pliable-statistics** [comment]
PDF downloading doesn't work because app sends http requests to http://arxiv.org, but arxiv
redirects these requests to https://arxiv.org. As a result instead of
pdf file app downloads a error message "Moved Permanently".

**Comment by pliable-statistics** [comment]
> Apparently, all articles are showing up as 0.0MB as well.
that's why you guys are unable to open a file - it is because file consist of error message "Moved permanently".

**Comment by jdeslip** [comment]
Hey All,

Sorry. I fixed this in the play store about a year ago. I just updated the code. Thanks @pliable-statistics your fix was basically the same as mine.

My github account was accidentally ignoring these comments. :/ Fixed now I think.

Jack

**Comment by jdeslip** [comment]
I think the Google Code exporter had set my account up to ignore the arxiv-mobile project on import for some reason. I just figured nobody cared. ;)
